service: serverless-lambda-service

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: ">=2.53.0"

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-2
  memorySize: 256
  timeout: 10

# you can add packaging information here
package:
  exclude:
    - reports/**
    - package-lock.json
    - .gitignore

functions:
  app:
    handler: index.handler
    description: ExpressJS Middleware for routing
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
